# Generated by Django 5.2.3 on 2025-07-01 00:41

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='total_sum',
        ),
        migrations.AddField(
            model_name='order',
            name='total_sum',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='customer',
            name='phone',
            field=models.CharField(blank=True, max_length=20, null=True, validators=[django.core.validators.RegexValidator(message="Phone number must be in the format: '+1234567890' or '123-456-7890'", regex='^(\\+\\d{1,4}\\d{7,14}|\\d{3}-\\d{3}-\\d{4})$')]),
        ),
    ]
